# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 02:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('digitalsignature', '0004_auto_20171027_0220'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractParty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalsignature.Template')),
            ],
        ),
        migrations.CreateModel(
            name='AbstractSignature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.FloatField(default=0)),
                ('left', models.FloatField(default=0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalsignature.Page')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalsignature.AbstractParty')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalsignature.Template')),
            ],
        ),
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalsignature.Document')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.FloatField(default=0)),
                ('left', models.FloatField(default=0)),
                ('sign', models.FileField(null=True, upload_to='')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalsignature.Document')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalsignature.Page')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalsignature.Party')),
            ],
        ),
    ]
