# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 09:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalsignature', '0006_auto_20171027_0829'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pdf',
            old_name='page_height',
            new_name='pageHeight',
        ),
        migrations.RenameField(
            model_name='pdf',
            old_name='page_width',
            new_name='pageWidth',
        ),
    ]
